apiVersion: apps/v1
kind: Deployment
metadata:
  name: marry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marry
  template:
    metadata:
      labels:
        app: marry
    spec:
      containers:
      - image: okteto.dev/marry:latest
        name: marry
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "da5aa6ac-ecf9-496b-8a63-77189cd401a1"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "1577a1d4-a078-4dd9-858b-2d6657f71703"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
